Ensure archive_dir is present
ansible-middleware/wildfly pull request #19
Opened 2022-02-14 05:28 UTC by aushacker

Fixes #16 .

2022-02-21 08:33 UTC, rpelisse approved these changes

2022-02-23 15:49 UTC, guidograzioli requested changes

2022-02-23 15:49 UTC, guidograzioli commented on roles/wildfly_install/tasks/main.yml
> +
It's missing the mode here, let's make it 0644

2022-02-23 15:50 UTC, rpelisse commented
@aushacker can you udpate the PR? :)

2022-02-23 23:38 UTC, aushacker commented
@rpelisse Rebased branch issue_16 to latest main and applied the requested change. Not sure what I've broken.

2022-02-24 08:41 UTC, guidograzioli commented
> @rpelisse Rebased branch issue_16 to latest main and applied the requested change. Not sure what I've broken.

nothing serious broke, after you rebase you got the settings for the ansible-lint execution, and a linter is not happy about
a task name here https://github.com/ansible-middleware/wildfly/pull/19/files/fda0a25bb82edd4c33cd269f2694ac3ed5f2d412#diff-0046cb8a23c7e3b529a42af5ae1e2b70a389df9d466d320bae13811879e4218dR13 (wants "Ensure" not "Ensures; I know it may seem a silly rule, we should set it only as a warning)

2022-02-24 08:43 UTC, rpelisse commented
@guidograzioli I think @aushacker refers to the fact that, now, this PR has **24 commits** in it. I think I will just cherry-pick the change and make a new PR.

2022-02-24 09:42 UTC, aushacker commented
Thanks @rpelisse. I've messed up the rebase somehow and commits from the divergent main branch got included.

2022-02-24 09:49 UTC, rpelisse commented
@aushacker don't worry, i'll cherry pick and make a new PR. Not sure when i'll come around it, but soon :)

2022-02-24 16:46 UTC, rpelisse commented
Superseeded by [PR](https://github.com/ansible-middleware/wildfly/pull/25)

2022-02-24 16:46 UTC, closed without merging