AMW-284 Not able to download EAP 8.0.0.Beta using redhat.eap collection
ansible-middleware/wildfly pull request #256
Opened 2024-08-05 11:32 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/AMW-284

2024-08-05 13:37 UTC, rpelisse requested changes
Let's see what Carlo says :)

2024-08-05 13:37 UTC, rpelisse commented on roles/wildfly_migration/templates/environment.properties.j2
> +modules.includes={{ wildfly_driver_module_name }}
This should not be part of this PR, but of  distinct PR (I know,...)

2024-08-05 13:37 UTC, rpelisse commented on roles/wildfly_utils/tasks/prospero/install.yml
> +    - eap_version != '8.0.0.Beta'
@wolfc Do we need to support 8.0.0.Beta? If so, I'll rebase and merge this PR, otherwise, I think we can close it (as Won't Do).

2024-08-05 13:54 UTC, RanabirChakraborty commented on roles/wildfly_migration/templates/environment.properties.j2
> +modules.includes={{ wildfly_driver_module_name }}
I have already rebased it and the change is already there. Don't know how come it came here. I'll check again.

2024-08-07 15:58 UTC, rpelisse commented
Won't Do

2024-08-07 15:58 UTC, closed without merging